language: android
jdk: oraclejdk8
cache: false
env:
  global:
    - ANDROID_API_LEVEL=23
    - ANDROID_BUILD_TOOLS_VERSION=23.0.2
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=8
before_script:
 - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
 - emulator -avd test -no-skin -no-audio -no-window &
 - curl http://is.gd/android_wait_for_emulator > android-wait-for-emulator
 - chmod u+x android-wait-for-emulator
 - ./android-wait-for-emulator
 - adb shell input keyevent 82 &
before_install:
 - chmod +x gradlew
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-23
    - sys-img-x86-android-23